# Visit https://github.com/lowlighter/metrics/blob/master/action.yml for full reference
name: Metrics
on:
  # Schedule updates (each hour)
  schedule: [{cron: "0 1 * * *"}]
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          # Your GitHub token
          token: ${{ secrets.METRICS_TOKEN }}

          # Options
          user: mgmadvance
          template: classic
          base: header, activity, community, repositories, metadata
          config_padding: 0, 22%
          config_timezone: America/Sao_Paulo
          plugin_followup: yes
          plugin_followup_sections: repositories
          plugin_gists: yes
          plugin_lines: yes
          plugin_rss: yes
          plugin_rss_limit: 4
          plugin_rss_source: https://mgmadvance.github.io/feed.xml
          repositories_forks: yes
